FROM --platform=$BUILDPLATFORM debian:13-slim

ARG TARGETARCH
ENV DEBIAN_FRONTEND=noninteractive

# -----------------------------------------------------------------------------
# 使用阿里源
# -----------------------------------------------------------------------------
RUN rm -f /etc/apt/sources.list.d/*.sources && \
    printf '%s\n' \
    "Types: deb" \
    "URIs: http://mirrors.aliyun.com/debian" \
    "Suites: trixie trixie-updates" \
    "Components: main contrib non-free non-free-firmware" \
    "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" \
    > /etc/apt/sources.list.d/debian.sources && \
    printf '%s\n' \
    "" \
    "Types: deb" \
    "URIs: http://mirrors.aliyun.com/debian-security" \
    "Suites: trixie-security" \
    "Components: main contrib non-free non-free-firmware" \
    "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" \
    >> /etc/apt/sources.list.d/debian.sources

# -----------------------------------------------------------------------------
# 基础工具
# -----------------------------------------------------------------------------
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    make \
    cmake \
    ninja-build \
    git \
    curl \
    wget \
    unzip \
    xz-utils \
    python3 \
    python3-pip \
    python3-venv \
    pkg-config \
    ca-certificates \
    gdb-multiarch \
    openocd \
    stlink-tools \
    libusb-1.0-0-dev \
    usbutils \
    file && \
    rm -rf /var/lib/apt/lists/*

# -----------------------------------------------------------------------------
# 拷贝 ARM Toolchain
# -----------------------------------------------------------------------------
COPY toolchains/ ./tmp/toolchains/

ARG GCC_VERSION=14.3.rel1

RUN if [ "$TARGETARCH" = "amd64" ]; then \
    FILE=arm-gnu-toolchain-${GCC_VERSION}-x86_64-arm-none-eabi.tar.xz; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
    FILE=arm-gnu-toolchain-${GCC_VERSION}-aarch64-arm-none-eabi.tar.xz; \
    else \
    echo "Unsupported architecture: $TARGETARCH"; \
    exit 1; \
    fi && \
    mkdir -p /opt && \
    tar -xf /tmp/toolchains/${FILE} -C /opt && \
    TOOLCHAIN_DIR=$(find /opt -maxdepth 1 -type d -name "arm-gnu-toolchain-*") && \
    ln -s "$TOOLCHAIN_DIR" /opt/arm-gcc && \
    rm -rf /tmp/toolchains

ENV PATH="/opt/arm-gcc/bin:${PATH}"

# -----------------------------------------------------------------------------
# 验证
# -----------------------------------------------------------------------------
RUN arm-none-eabi-gcc --version && \
    arm-none-eabi-gcc -print-sysroot

WORKDIR /workspaces

CMD ["/bin/bash"]